export const COM_CREATE_REQUEST = 'COM_CREATE_REQUEST'
export const COM_CREATE_RESPONSE = 'COM_CREATE_RESPONSE'
export const COM_CREATE_FAIL = 'COM_CREATE_REQUEST'

export const COM_LIST_REQUEST = 'COM_LIST_REQUEST'
export const COM_LIST_RESPONSE = 'COM_LIST_RESPONSE'
export const COM_LIST_FAIL = 'COM_LIST_REQUEST'