export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_RESPONSE = 'POST_CREATE_RESPONSE'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'

export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_RESPONSE = 'POST_LIST_RESPONSE'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_RESPONSE = 'POST_DELETE_RESPONSE'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'