export const USER_STATE_REQUEST = 'USER_STATE_REQUEST'
export const USER_STATE_RESPONSE = 'USER_STATE_RESPONSE'
export const USER_STATE_FAIL = 'USER_STATE_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_RESPONSE = 'USER_REGISTER_RESPONSE'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_RESPONSE = 'USER_LOGIN_RESPONSE'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_GOOGLE_LOGIN_REQUEST = 'USER_GOOGLE_LOGIN_REQUEST'
export const USER_GOOGLE_LOGIN_RESPONSE = 'USER_GOOGLE_LOGIN_RESPONSE'
export const USER_GOOGLE_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL'

